apiVersion: v1
description: A Helm chart for Kubernetes
name: kube-keepalived-vip
version: 0.1.0
sources:
- https://github.com/aledbf/kube-keepalived-vip
- https://github.com/munnerz/keepalived-cloud-provider